// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyRequest(arg1) {
  return window['go']['main']['App']['CopyRequest'](arg1);
}

export function CreateEnvironment(arg1, arg2) {
  return window['go']['main']['App']['CreateEnvironment'](arg1, arg2);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateProjectScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProjectScript'](arg1, arg2, arg3);
}

export function CreateRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateRequest'](arg1, arg2, arg3, arg4);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProjectScript(arg1, arg2) {
  return window['go']['main']['App']['DeleteProjectScript'](arg1, arg2);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function ExecuteCurl(arg1) {
  return window['go']['main']['App']['ExecuteCurl'](arg1);
}

export function ExecuteHTTPRequest(arg1) {
  return window['go']['main']['App']['ExecuteHTTPRequest'](arg1);
}

export function ExtractVariables(arg1) {
  return window['go']['main']['App']['ExtractVariables'](arg1);
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetGlobalVariables() {
  return window['go']['main']['App']['GetGlobalVariables']();
}

export function GetProjectTree(arg1) {
  return window['go']['main']['App']['GetProjectTree'](arg1);
}

export function GetProjectsDir() {
  return window['go']['main']['App']['GetProjectsDir']();
}

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function ImportPostmanCollection(arg1) {
  return window['go']['main']['App']['ImportPostmanCollection'](arg1);
}

export function ListProjectScripts(arg1) {
  return window['go']['main']['App']['ListProjectScripts'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function LoadAppConfig() {
  return window['go']['main']['App']['LoadAppConfig']();
}

export function LoadEnvironments() {
  return window['go']['main']['App']['LoadEnvironments']();
}

export function LoadProjectGroupsState() {
  return window['go']['main']['App']['LoadProjectGroupsState']();
}

export function MoveFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2);
}

export function MoveRequest(arg1, arg2) {
  return window['go']['main']['App']['MoveRequest'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function RenameRequest(arg1, arg2) {
  return window['go']['main']['App']['RenameRequest'](arg1, arg2);
}

export function ReplaceVariables(arg1, arg2) {
  return window['go']['main']['App']['ReplaceVariables'](arg1, arg2);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveGlobalVariables(arg1) {
  return window['go']['main']['App']['SaveGlobalVariables'](arg1);
}

export function SaveProjectGroupsState(arg1) {
  return window['go']['main']['App']['SaveProjectGroupsState'](arg1);
}

export function UpdateEnvironment(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEnvironment'](arg1, arg2, arg3);
}

export function UpdateProjectScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProjectScript'](arg1, arg2, arg3, arg4);
}

export function UpdateRequest(arg1, arg2) {
  return window['go']['main']['App']['UpdateRequest'](arg1, arg2);
}

export function UpdateRequestScripts(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateRequestScripts'](arg1, arg2, arg3);
}
