// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGlobalCookies(arg1) {
  return window['go']['main']['App']['AddGlobalCookies'](arg1);
}

export function AddRequestCase(arg1, arg2) {
  return window['go']['main']['App']['AddRequestCase'](arg1, arg2);
}

export function BatchExecuteHTTPRequests(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BatchExecuteHTTPRequests'](arg1, arg2, arg3, arg4);
}

export function CancelCurrentRequest() {
  return window['go']['main']['App']['CancelCurrentRequest']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CopyRequest(arg1) {
  return window['go']['main']['App']['CopyRequest'](arg1);
}

export function CreateEnvironment(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateEnvironment'](arg1, arg2, arg3);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateGitBranch(arg1) {
  return window['go']['main']['App']['CreateGitBranch'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateProjectScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProjectScript'](arg1, arg2, arg3, arg4);
}

export function CreateRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateRequest'](arg1, arg2, arg3, arg4);
}

export function DeleteEnvironment(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1, arg2);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteGitBranch(arg1) {
  return window['go']['main']['App']['DeleteGitBranch'](arg1);
}

export function DeleteGlobalCookie(arg1) {
  return window['go']['main']['App']['DeleteGlobalCookie'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProjectScript(arg1, arg2) {
  return window['go']['main']['App']['DeleteProjectScript'](arg1, arg2);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function DeleteRequestCase(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequestCase'](arg1, arg2);
}

export function DisableGitSync() {
  return window['go']['main']['App']['DisableGitSync']();
}

export function DuplicateRequestCase(arg1, arg2) {
  return window['go']['main']['App']['DuplicateRequestCase'](arg1, arg2);
}

export function EnableGitSync(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnableGitSync'](arg1, arg2, arg3);
}

export function ExecuteCurl(arg1) {
  return window['go']['main']['App']['ExecuteCurl'](arg1);
}

export function ExecuteHTTPRequest(arg1) {
  return window['go']['main']['App']['ExecuteHTTPRequest'](arg1);
}

export function ExecuteHTTPRequestWithScripts(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ExecuteHTTPRequestWithScripts'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ExtractVariables(arg1) {
  return window['go']['main']['App']['ExtractVariables'](arg1);
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetCurrentGitBranch() {
  return window['go']['main']['App']['GetCurrentGitBranch']();
}

export function GetFolderScripts(arg1) {
  return window['go']['main']['App']['GetFolderScripts'](arg1);
}

export function GetFolderScriptsResult(arg1) {
  return window['go']['main']['App']['GetFolderScriptsResult'](arg1);
}

export function GetGlobalVariables() {
  return window['go']['main']['App']['GetGlobalVariables']();
}

export function GetHistoryEntry(arg1) {
  return window['go']['main']['App']['GetHistoryEntry'](arg1);
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetProjectScripts(arg1) {
  return window['go']['main']['App']['GetProjectScripts'](arg1);
}

export function GetProjectScriptsResult(arg1) {
  return window['go']['main']['App']['GetProjectScriptsResult'](arg1);
}

export function GetProjectTree(arg1) {
  return window['go']['main']['App']['GetProjectTree'](arg1);
}

export function GetProjectsDir() {
  return window['go']['main']['App']['GetProjectsDir']();
}

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function ImportOpenAPICollection(arg1) {
  return window['go']['main']['App']['ImportOpenAPICollection'](arg1);
}

export function ImportPostmanCollection(arg1) {
  return window['go']['main']['App']['ImportPostmanCollection'](arg1);
}

export function InitGitRepo() {
  return window['go']['main']['App']['InitGitRepo']();
}

export function InitProjectsDir() {
  return window['go']['main']['App']['InitProjectsDir']();
}

export function ListGitBranches() {
  return window['go']['main']['App']['ListGitBranches']();
}

export function ListHistory(arg1) {
  return window['go']['main']['App']['ListHistory'](arg1);
}

export function ListProjectScripts(arg1) {
  return window['go']['main']['App']['ListProjectScripts'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListProjectsForMCP() {
  return window['go']['main']['App']['ListProjectsForMCP']();
}

export function LoadAppConfig() {
  return window['go']['main']['App']['LoadAppConfig']();
}

export function LoadEnvironments(arg1) {
  return window['go']['main']['App']['LoadEnvironments'](arg1);
}

export function LoadGlobalCookies() {
  return window['go']['main']['App']['LoadGlobalCookies']();
}

export function LoadMCPConfig() {
  return window['go']['main']['App']['LoadMCPConfig']();
}

export function LoadProjectGroupsState() {
  return window['go']['main']['App']['LoadProjectGroupsState']();
}

export function MoveFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2, arg3);
}

export function MoveRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveRequest'](arg1, arg2, arg3);
}

export function ParseOpenAPICollection(arg1) {
  return window['go']['main']['App']['ParseOpenAPICollection'](arg1);
}

export function PullGitRepo() {
  return window['go']['main']['App']['PullGitRepo']();
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function RenameRequest(arg1, arg2) {
  return window['go']['main']['App']['RenameRequest'](arg1, arg2);
}

export function RenameRequestCase(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRequestCase'](arg1, arg2, arg3);
}

export function ReplaceVariables(arg1, arg2) {
  return window['go']['main']['App']['ReplaceVariables'](arg1, arg2);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveGlobalCookies(arg1) {
  return window['go']['main']['App']['SaveGlobalCookies'](arg1);
}

export function SaveGlobalVariables(arg1) {
  return window['go']['main']['App']['SaveGlobalVariables'](arg1);
}

export function SaveMCPConfig(arg1) {
  return window['go']['main']['App']['SaveMCPConfig'](arg1);
}

export function SaveProjectGroupsState(arg1) {
  return window['go']['main']['App']['SaveProjectGroupsState'](arg1);
}

export function SearchHistory(arg1, arg2) {
  return window['go']['main']['App']['SearchHistory'](arg1, arg2);
}

export function StartMCP() {
  return window['go']['main']['App']['StartMCP']();
}

export function StopMCP() {
  return window['go']['main']['App']['StopMCP']();
}

export function SwitchGitBranch(arg1) {
  return window['go']['main']['App']['SwitchGitBranch'](arg1);
}

export function SyncAllProjectsToGit() {
  return window['go']['main']['App']['SyncAllProjectsToGit']();
}

export function SyncProjectToGit(arg1) {
  return window['go']['main']['App']['SyncProjectToGit'](arg1);
}

export function UpdateEnvironment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateEnvironment'](arg1, arg2, arg3, arg4);
}

export function UpdateFolderScripts(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateFolderScripts'](arg1, arg2, arg3);
}

export function UpdateProjectScript(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProjectScript'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateProjectScripts(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProjectScripts'](arg1, arg2, arg3);
}

export function UpdateRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateRequest'](arg1, arg2, arg3, arg4);
}

export function UpdateRequestScripts(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateRequestScripts'](arg1, arg2, arg3);
}
