// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {project} from '../models';
import {config} from '../models';

export function AddRequestCase(arg1:string,arg2:string):Promise<models.CurlRequest>;

export function CopyRequest(arg1:string):Promise<models.CurlRequest>;

export function CreateEnvironment(arg1:string,arg2:string,arg3:Record<string, string>):Promise<models.Environment>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<models.Folder>;

export function CreateProject(arg1:string):Promise<models.Project>;

export function CreateProjectScript(arg1:string,arg2:string,arg3:string):Promise<models.ProjectScript>;

export function CreateRequest(arg1:string,arg2:string,arg3:string,arg4:models.HttpRequestSpec):Promise<models.CurlRequest>;

export function DeleteEnvironment(arg1:string,arg2:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteProjectScript(arg1:string,arg2:string):Promise<void>;

export function DeleteRequest(arg1:string):Promise<void>;

export function DeleteRequestCase(arg1:string,arg2:string):Promise<models.CurlRequest>;

export function DuplicateRequestCase(arg1:string,arg2:string):Promise<models.CurlRequest>;

export function ExecuteCurl(arg1:string):Promise<models.CurlResponse>;

export function ExecuteHTTPRequest(arg1:models.HttpRequestSpec):Promise<models.CurlResponse>;

export function ExecuteHTTPRequestWithScripts(arg1:string,arg2:string,arg3:models.HttpRequestSpec,arg4:Array<string>,arg5:Array<string>):Promise<models.CurlResponse>;

export function ExecuteHTTPRequestWithScriptsInline(arg1:string,arg2:string,arg3:models.HttpRequestSpec,arg4:string,arg5:string):Promise<models.CurlResponse>;

export function ExtractVariables(arg1:string):Promise<Array<string>>;

export function GetConfigDir():Promise<string>;

export function GetGlobalVariables():Promise<Record<string, string>>;

export function GetProjectTree(arg1:string):Promise<project.ProjectTree>;

export function GetProjectsDir():Promise<string>;

export function GetRequest(arg1:string):Promise<models.CurlRequest>;

export function ImportPostmanCollection(arg1:string):Promise<models.Project>;

export function InitGitRepo():Promise<void>;

export function ListProjectScripts(arg1:string):Promise<Array<models.ProjectScript>>;

export function ListProjects():Promise<Array<models.Project>>;

export function LoadAppConfig():Promise<config.AppConfig>;

export function LoadEnvironments(arg1:string):Promise<Array<models.Environment>>;

export function LoadProjectGroupsState():Promise<project.ProjectGroupsState>;

export function MoveFolder(arg1:string,arg2:string,arg3:string):Promise<string>;

export function MoveRequest(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RenameFolder(arg1:string,arg2:string):Promise<models.Folder>;

export function RenameProject(arg1:string,arg2:string):Promise<models.Project>;

export function RenameRequest(arg1:string,arg2:string):Promise<models.CurlRequest>;

export function RenameRequestCase(arg1:string,arg2:string,arg3:string):Promise<models.CurlRequest>;

export function ReplaceVariables(arg1:string,arg2:Record<string, string>):Promise<string>;

export function SaveAppConfig(arg1:config.AppConfig):Promise<void>;

export function SaveGlobalVariables(arg1:Record<string, string>):Promise<void>;

export function SaveProjectGroupsState(arg1:project.ProjectGroupsState):Promise<void>;

export function SyncAllProjectsToGit():Promise<void>;

export function SyncProjectToGit(arg1:string):Promise<void>;

export function UpdateEnvironment(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<void>;

export function UpdateProjectScript(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.ProjectScript>;

export function UpdateRequest(arg1:string,arg2:models.HttpRequestSpec,arg3:Array<models.HttpRequestCase>,arg4:string):Promise<void>;

export function UpdateRequestScripts(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<void>;
